Blocks = new Meteor.Collection('blocks')
Comments = new Meteor.Collection('comments')
Hearts = new Meteor.Collection('hearts')
Ratings = new Meteor.Collection('ratings')
Reports = new Meteor.Collection('reports')
Shares = new Meteor.Collection('shares')
Views = new Meteor.Collection('views')